### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#5]
Completely missed the prereqs, now can't start CM.  

2016-09-22 17:32:27,644 INFO ScheduledStalenessChecker:com.cloudera.cmf.service.ServiceHandlerRegistry: Executing command ProcessStalenessCheckCommand BasicCmdArgs{args=[First reason why: Client config (id=9, host id=5) has a brand new heartbeat]}.
2016-09-22 17:32:27,935 INFO ProcessStalenessDetector-0:com.cloudera.cmf.service.config.components.ProcessStalenessDetector: Staleness check done. Duration: PT0.268S 
2016-09-22 17:32:30,980 INFO CMMetricsForwarder-0:com.cloudera.server.cmf.components.ClouderaManagerMetricsForwarder: Failed to send metrics.
java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy104.writeMetrics(Unknown Source)
        at com.cloudera.server.cmf.components.ClouderaManagerMetricsForwarder.sendWithAvro(ClouderaManagerMetricsForwarder.java:325)
        at com.cloudera.server.cmf.components.ClouderaManagerMetricsForwarder.sendMetrics(ClouderaManagerMetricsForwarder.java:312)
        at com.cloudera.server.cmf.components.ClouderaManagerMetricsForwarder.run(ClouderaManagerMetricsForwarder.java:146)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.avro.AvroRemoteException: java.net.ConnectException: Connection refused
        at org.apache.avro.ipc.specific.SpecificRequestor.invoke(SpecificRequestor.java:88)
        ... 11 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1091)
        at org.apache.avro.ipc.HttpTransceiver.writeBuffers(HttpTransceiver.java:71)
        at org.apache.avro.ipc.Transceiver.transceive(Transceiver.java:58)
        at org.apache.avro.ipc.Transceiver.transceive(Transceiver.java:72)
        at org.apache.avro.ipc.Requestor.request(Requestor.java:147)
        at org.apache.avro.ipc.Requestor.request(Requestor.java:101)
        at org.apache.avro.ipc.specific.SpecificRequestor.invoke(SpecificRequestor.java:72)
        ... 11 more

**Comment by irxbacon** [comment]
And... I'm back in CM.  Looks like deleting the TLS flag in mysql fixed that part.  Now i'm on to getting the kerberos keytab set up.

**Comment by irxbacon** [comment]
Generated and placed .cer file on each node, entered into keystore

**Comment by irxbacon** [comment]
keytool -import -alias vtrhyno_keystore -file ~/selfsigned.cer -keystore $JAVA_HOME/jre/lib/security/jssecacerts -storepass changeit

**Comment by irxbacon** [comment]
addprinc -randkey hdfs/ip-10-0-1-124.ec2.internal@VTRHYNO.COM
 addprinc -randkey mapred/ip-10-0-1-124.ec2.internal@VTRHYNO.COM
 addprinc -randkey yarn/ip-10-0-1-124.ec2.internal@VTRHYNO.COM
 addprinc -randkey HTTP/ip-10-0-1-124.ec2.internal@VTRHYNO.COM

xst -norandkey -k hdfs.keytab hdfs/ip-10-0-1-124.ec2.internal HTTP/ip-10-0-1-124.ec2.internal
xst -norandkey -k mapred.keytab mapred/ip-10-0-1-124.ec2.internal HTTP/ip-10-0-1-124.ec2.internal
xst -norandkey -k yarn.keytab yarn/ip-10-0-1-124.ec2.internal HTTP/ip-10-0-1-124.ec2.internal

**Comment by irxbacon** [comment]
Somehow managed to prevent all 3 zookeeper instances from being able to authenticate.  This sounds like tomorrow/next week's learning opportunity.

**Comment by mfernest** [comment]
Wow, I did not think enabling TLS would throw this big a wrench into the works. I'm counting effort for that part of the lab. What a mess.

Completed
